### ISSUE TITLE
spring boot 的 dubbo配置问题

### ISSUE THREAD

**Issue by hao96** [hao96/spring-boot#3]
在检查 dubbo的maven依赖、配置文件的配置、dubbo注解的写法都没问题后，感觉还是没有注册成功。
maven依赖：
```
       <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>0.2.0</version>
        </dependency>
```
配置文件：
```
# ===============================
# = Dubbo
# ===============================
dubbo:
  protocol:
    port: -1
    id: dubbo
    name: dubbo
  application:
    id: work-station
    name: work-station
  registry:
    id: my-registry
    address: zookeeper://192.168.1.200:2181
  scan:
    basePackages: com.hao
```
dubbo注解：
`@Service(version = "1.0.0")`

最后将项目与已有的项目仔细对比，发现原来的项目的配置文件名为：`application.yaml`，而这项目中使用的配置文件名为：`application.properties`，将配置文件名、格式修改后，dubbo服务注册成功了！
